import time
import os

print("Starting Virus.exe")
time.sleep(2)
print("scaning for persanal data")
time.sleep(2)
print("found persanal data")
time.sleep(2)
print("copying persanal data")
time.sleep(2)
print("sending persanal data to main virus servers")
time.sleep(2)
print("scaning for google chrome")
time.sleep(2)
print("google chrome not found")
time.sleep(2)
print("scaning for microsoft edge")
time.sleep(2)
print("microsoft edge not found")
time.sleep(2)
print("scaning for firefox")
time.sleep(2)
print("firefox found")
time.sleep(2)
print("scaning for passwords")
time.sleep(2)
print("copying passwords")
time.sleep(2)
print("scaning for bank information")
time.sleep(2)
print("copying bank information")
time.sleep(2)
print("sending passwords and bank information to main virus servers")
time.sleep(2)
print("scaning for roblox")
time.sleep(2)
print("taking robux")
time.sleep(2)
print("scaning for McAfee")
time.sleep(2)
print("deleting McAfee")
time.sleep(2)
print("finishing up")
time.sleep(2)
print("deleting virus.exe")
time.sleep(2)
virusdata = open("virusdata.txt","w+")
virusdata.write("persanal data-")
virusdata.write("\n")
virusdata.write("name:Bob bobington")
virusdata.write("\n")
virusdata.write("age:69y, 7m, 24d")
virusdata.write("\n")
virusdata.write("social security:75046763906756")
virusdata.write("\n")
virusdata.write("\n")
virusdata.write("passwords-")
virusdata.write("\n")
virusdata.write("amazon:Password")
virusdata.write("\n")
virusdata.write("microsoft:Password")
virusdata.write("\n")
virusdata.write("Roblox:Password")
virusdata.write("\n")
virusdata.write("Minecraft:Password")
virusdata.write("\n")
virusdata.write("Mc Meats:Password")
virusdata.write("\n")
virusdata.write("\n")
virusdata.write("bank information-")
virusdata.write("\n")
virusdata.write("bank:BankofBobington")
virusdata.write("\n")
virusdata.write("password:Password!butsecure_BankPassWArd")
virusdata.write("\n")
virusdata.write("credit account money:-158.94")
virusdata.write("\n")
virusdata.write("savings account money:6493.52")
virusdata.write("\n")
virusdata.write("\n")
virusdata.write("roblox-")
virusdata.write("\n")
virusdata.write("robux:28584749")
virusdata.close()
os.remove("Not a virus.py")
